config/routes.rb
Frasernw::Application.routes.draw do

  resources :reviews, :only => [:index, :destroy] do
    put :accept
  end

  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  match "/versions"                 => "versions#show_all", :as => "all_versions"
  match "/specialists/:id/versions" => "versions#index",    :as => "show_versions", :model => 'specialists'
  match "/versions/:id"             => "versions#show",     :as => "show_version"

  resources :specializations do
    resources :specialists
    resources :procedures
    resources :clinics
  end
  resources :clinics
  resources :specialists
  resources :procedures
  resources :hospitals

  match "tracker" => 'tracker#index', :as => 'tracker'
  
  match "specializations/:id/showalt" => 'specializations#showalt'
  
  match "specialists/:id/:token/edit"   => 'specialists_editor#edit',  :as => 'specialist_self_edit'
  put  "specialists/:id/:token/update" => 'specialists_editor#update', :as => 'specialist_self_update'
  post  "specialists/email/:id"         => 'specialists#email', :as => 'specialist_email'
  
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'login' => 'user_sessions#new', :as => :login

  resources :user_sessions

  resources :users

  match 'searchtree'  => 'searchdoc#tree',  :as => :searchtree
  match 'searchindex' => 'searchdoc#index', :as => :searchindex
  match 'navigation' => 'searchdoc#navigation', :as => :navigation

  root :to => 'specializations#index'

end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
  attr_accessible :name, :address1, :address2, :postalcode, :city, :province, :phone1, :fax, :status, :interest, :waittime, :specialization_id, :referral_criteria, :referral_process, :procedure_ids, :responds_via
  has_paper_trail meta: { to_review: false }
  
  has_many :attendances
  has_many :specialists, :through => :attendances
  
  belongs_to :specialization
  
  validates_presence_of :specialization_id, :on => :create, :message => "can't be blank"
  validates_presence_of :name, :on => :create, :message => "can't be blank"
  
  # specialists have the capacity to perform procedures
  has_many   :focuses
  has_many   :procedures, :through => :focuses
  
  def address
    address = ''
    address += self.address1 || ''
    address += self.address2 || ''
    address
  end
    
  def waittime_with_units
    self.waittime.presence ? self.waittime.to_s() + " weeks" : "n/a"
  end

end

app/models/specialization.rb
class Specialization < ActiveRecord::Base
  attr_accessible :name
  has_paper_trail meta: { to_review: false }
  
  has_many :specialists
  has_many :clinics
  has_many :procedures

  default_scope order('name')

end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  load_and_authorize_resource

  def index
    unless params[:specialization_id]
      redirect_to specializations_path, :notice => "Need to specify a specialization" and return
    else
      @specialization = Specialization.find(params[:specialization_id])
      @clinics = Clinic.all
    end
  end

  def show
    @clinic = Clinic.find(params[:id])
    render :layout => false if request.headers['X-PJAX']
  end

  def new
    unless params[:specialization_id]
      redirect_to specializations_path, :notice => "Need to specify a specialization" and return
    else
      @specialization = Specialization.find(params[:specialization_id])
      @clinic = Clinic.new(:specialization_id => params[:specialization_id])
    end
  end

  def create
    @clinic = Clinic.new(params[:clinic])
    if @clinic.save
      redirect_to specialization_clinic_path(@clinic.specialization, @clinic), :notice => "Successfully created clinic."
    else
      @specialization = Specialization.find(params[:specialization_id])
      render :action => 'new'
    end
  end

  def edit
    @clinic = Clinic.find(params[:id])
  end

  def update
    params[:clinic][:procedure_ids] ||= []
    @clinic = Clinic.find(params[:id])
    if @clinic.update_attributes(params[:clinic])
      redirect_to @clinic, :notice  => "Successfully updated clinic."
    else
      @specialization = Specialization.find(params[:specialization_id])
      render :action => 'edit'
    end
  end

  def destroy
    @clinic = Clinic.find(params[:id])
    @clinic.destroy
    redirect_to clinics_url, :notice => "Successfully destroyed clinic."
  end
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/views/clinics/_form.html.haml
= form_for @clinic do |f|
  = f.error_messages
  %p
    = f.label :name
    %br
    = f.text_field :name
  %p
    = f.label :address1
    %br
    = f.text_field :address1
  %p
    = f.label :address2
    %br
    = f.text_field :address2
  %p
    = f.label :postalcode
    %br
    = f.text_field :postalcode
  %p
    = f.label :city
    %br
    = f.text_field :city
  %p
    = f.label :province
    %br
    = f.text_field :province
  %p
    = f.label :phone1
    %br
    = f.text_field :phone1
  %p
    = f.label :fax
    %br
    = f.text_field :fax
  %p
    = f.label :status
    %br
    = f.text_area :status
  %p
    = f.label :responds_via, "How does the clinic respond to referral requests (phone to GP office, fax to GP office, phone to patient, other...)"
    %br
    = f.text_area :responds_via
  %p
    = f.label :interest
    %br
    = f.text_area :interest
  %p
    = f.label :referral_criteria
    %br
    = f.text_area :referral_criteria, :id => :referral_criteria
  %p
    = f.label :referral_process
    %br
    = f.text_area :referral_process, :id => :referral_process
  %p
    = f.label :waittime
    %br
    = f.number_field :waittime
  %p
    = f.label :procedures, "Scope of practice"
    %br
    - @clinic.specialization.procedures.where(:done_by_clinics => true).each do |procedure|
      %br
      = check_box_tag :procedure_ids, procedure.id, @clinic.procedures.include?(procedure), :name => 'clinic[procedure_ids][]'
      = label_tag :procedure_ids, procedure.name
      / FIXME - this should probably be done as specialists - hidden field
      = f.hidden_field :specialization_id

    %p
    = f.submit

app/views/clinics/edit.html.haml
- title "Edit Clinic"

= render 'form'

%p
  = link_to "Show", @clinic
  |
  = link_to "View All", clinics_path

app/views/clinics/index.html.haml
- title "Clinics"

%table
  %tr
    %th Name
    %th Address1
    %th Address2
    %th Postalcode
    %th City
    %th Province
  - for clinic in @clinics
    %tr
      %td= clinic.name
      %td= clinic.address1
      %td= clinic.address2
      %td= clinic.postalcode
      %td= clinic.city
      %td= clinic.province
      %td= link_to 'Show', clinic
      %td= link_to 'Edit', edit_clinic_path(clinic)
      %td= link_to 'Destroy', clinic, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Clinic", new_clinic_path

app/views/clinics/new.html.haml
- title "New Clinic"

= render 'form'

%p= link_to "Back to List", clinics_path

app/views/clinics/show.html.haml
/ - title "Specialist"

%h1
  = @clinic.name
  
#address.collapseup
  = @clinic.address.strip + ", " + @clinic.city.strip + ', ' + @clinic.province.strip + ', ' +  @clinic.postalcode
  
#phone
  %strong Phone:
  = @clinic.phone1.presence || "unknown"
 
#fax.collapseup
  %strong Fax:
  = @clinic.fax.presence || "unknown"

#responds_via.collapseup
  %strong Responds via:
  = @clinic.responds_via.presence || "unspecified"
  
#status
  %strong Status:
  = @clinic.status

#wait_time
  %strong Average wait time:
  = (@clinic.waittime.to_s().presence || "unknown") + " weeks"

#referral_criteria
  %strong Referral Criteria:
  = @clinic.referral_criteria.presence || "unspecified"

#referral_process
  %strong Referral Process:
  = @clinic.referral_process.presence || "unspecified"
  
#scope
  %strong Scope of practice:
  - if @clinic.procedures.empty? 
    unspecified
  - else 
    %ul
      - @clinic.procedures.each do |procedure|
        %li= procedure.name

#attending_physicians
  %strong Attending physicians:
  - if @clinic.specialists.empty? 
    unspecified
  - else 
    %ul
    - @clinic.specialists.each do |specialist|
      %li= link_to(specialist.name, url_for(specialist))

#edit
  = link_to "Edit", edit_specialization_clinic_path(@clinic.specialization, @clinic)
  |
  = link_to "Destroy", @clinic, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All #{@clinic.specialization.name}", specialization_path(@clinic.specialization)
  / |
  / # = link_to "View All Specialists", specialists_path