config/routes.rb
Frasernw::Application.routes.draw do

  resources :reviews, :only => [:index, :destroy] do
    put :accept
  end

  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  match "/versions"                 => "versions#show_all", :as => "all_versions"
  match "/specialists/:id/versions" => "versions#index",    :as => "show_versions", :model => 'specialists'
  match "/versions/:id"             => "versions#show",     :as => "show_version"

  resources :specializations do
    resources :specialists
    resources :procedures
    resources :clinics
  end
  resources :clinics
  resources :specialists
  resources :procedures
  resources :hospitals

  match "tracker" => 'tracker#index', :as => 'tracker'
  
  match "specializations/:id/showalt" => 'specializations#showalt'
  
  match "specialists/:id/:token/edit"   => 'specialists_editor#edit',  :as => 'specialist_self_edit'
  put  "specialists/:id/:token/update" => 'specialists_editor#update', :as => 'specialist_self_update'
  post  "specialists/email/:id"         => 'specialists#email', :as => 'specialist_email'
  
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'login' => 'user_sessions#new', :as => :login

  resources :user_sessions

  resources :users

  match 'searchtree'  => 'searchdoc#tree',  :as => :searchtree
  match 'searchindex' => 'searchdoc#index', :as => :searchindex
  match 'navigation' => 'searchdoc#navigation', :as => :navigation

  root :to => 'specializations#index'

end

app/models/specialist.rb
class Specialist < ActiveRecord::Base
    attr_accessible :firstname, :lastname, :address1, :address2, :postalcode, :city, :province, :phone1, :fax, :practise_limitations, :interest, :waittime, :specialization_id, :procedure_ids, :direct_phone, :red_flags, :clinic_ids, :responds_via, :contact_name, :contact_email, :contact_phone, :contact_notes, :referral_criteria, :status_mask, :location_opened, :referral_fax, :referral_phone, :referral_other_details, :urgent_fax, :urgent_phone, :urgent_other_details, :respond_by_fax, :respond_by_phone, :respond_by_mail, :respond_to_patient, :status_details, :required_investigations, :not_performed, :lagtime, :patient_can_book, :lag_uom, :wait_uom, :referral_form, :hospital_ids, :capacities_attributes, :offices_attributes
    has_paper_trail ignore: :saved_token
    
    belongs_to :specialization
    
    # specialists have the capacity to perform procedures
    has_many   :capacities
    has_many   :procedures, :through => :capacities
    accepts_nested_attributes_for :capacities, :reject_if => lambda { |a| a[:procedure_id].blank? }, :allow_destroy => true
    
    # specialists attend clinics
    has_many   :attendances
    has_many   :clinics, :through => :attendances
    
    # specialists have "priviliges" at hospitals
    has_many   :privileges
    has_many   :hospitals, :through => :privileges
    
    # specialists are favorited by users of the system
    has_many   :favorites
    has_many   :users, :through => :favorites
    
    # has many contacts - dates and times they were contacted
    has_many  :contacts
    
    # dates and times they looked at and changed their own record
    has_many  :views
    has_many  :edits
    
    has_many :offices
    accepts_nested_attributes_for :offices
    
    validates_presence_of :firstname, :on => :save, :message => "can't be blank"
    validates_presence_of :lastname, :on => :save, :message => "can't be blank"
    validates_presence_of :specialization_id, :on => :save, :message => "can't be blank"
    
    after_initialize :default_values
    
    default_scope order('lastname, firstname')
    
    STATUS_HASH = { 1 => "Accepting new patients", 2 => "Only doing follow up on previous patients", 3 => "Semi-retired", 4 => "Retired"}
    
    def status
        Specialist::STATUS_HASH[status_mask]
    end
    
    def name
        firstname + ' ' + lastname
    end
    
    def address
        address = ''
        address += self.address1 || ''
        address += self.address2 || ''
        address
    end
    
    def lagtime_with_units
        self.lagtime.presence ? self.lagtime + " " + self.lag_uom : "n/a"
    end
    
    def waittime_with_units
        self.waittime.presence ? self.waittime + " " + self.wait_uom : "n/a"
    end
    
    def token
        if self.saved_token
            return self.saved_token
        else
            self.saved_token = SecureRandom.hex(16)
            self.save
            return self.saved_token
        end
    end
    
    def practice_limitations
        return practise_limitations
    end
    
    def accepts_referrals_via
        if referral_phone and referral_fax and referral_other_details.presence
            return "phone, fax, or " + referral_other_details
        elsif referral_phone and referral_fax
            return "phone or fax"
        elsif referral_phone
            output = "phone"
            if referral_other_details.presence
                return output + " or " + referral_other_details
            end
        elsif referral_fax
            output = "fax"
            if referral_other_details.presence
                return output + " or " + referral_other_details
            end
        elsif referral_other_details.presence
            return referral_other_details
        else
            return "unspecified"
        end
    end
    
    def responds_via
        if (not respond_by_phone) and (not respond_by_fax) and (not respond_by_mail) and (not respond_to_patient)
            return "unspecified"
        elsif (not respond_by_phone) and (not respond_by_fax) and (not respond_by_mail) and respond_to_patient
            return "directly to patient"
        else
            if respond_by_phone and respond_by_fax and respond_by_mail
                output = "phone, fax, or mail to referring office"
            elsif respond_by_phone and respond_by_fax and (not respond_by_mail)
                output = "phone or fax to referring office"
            elsif respond_by_phone and (not respond_by_fax) and respond_by_mail
                output = "phone or mail to referring office"
            elsif respond_by_phone and (not respond_by_fax) and (not respond_by_mail)
                output = "phone to referring office"
            elsif (not respond_by_phone) and respond_by_fax and respond_by_mail
                output = "fax or mail to referring office"
            elsif (not respond_by_phone) and respond_by_fax and (not respond_by_mail)
                output = "fax to referring office"
            else # must be (not respond_by_phone) and (not respond_by_fax) and respond_by_mail
                output = "mail to referring office"
            end
            
            if respond_to_patient
                return output + " (and directly to patient)"
            else
                return output
            end
        end
    end
    
    def urgent_referrals_via
        if urgent_phone and urgent_fax and urgent_other_details.presence
            return "phone, fax, or " + urgent_other_details
        elsif urgent_phone and urgent_fax
            return "phone or fax"
        elsif urgent_phone
            output = "phone"
            if urgent_other_details.presence
                return output + " or " + urgent_other_details
            end
        elsif urgent_fax
            output = "fax"
            if urgent_other_details.presence
                return output + " or " + urgent_other_details
            end
        elsif urgent_other_details.presence
            return referral_other_details
        else
            return "unspecified"
        end
    end
    
    private
    
    def default_values
        self.lag_uom ||= "weeks"
        self.wait_uom ||= "weeks"
    end
    
end

app/controllers/specialists_controller.rb
class SpecialistsController < ApplicationController
  load_and_authorize_resource

  def index
    # @specializations = Specialization.find(:all, :include => :specialists)
    redirect_to specializations_path, :notice => "Need to specify a specialization" unless params[:specialization_id]
    @specialization = Specialization.find(params[:specialization_id])
    @specialists = @specialization.specialists
  end

  def show
    @specialist = Specialist.find(params[:id])
    render :layout => false if request.headers['X-PJAX']
  end

  def new
    @specialization = Specialization.find(params[:specialization_id])
    @specialist     = @specialization.specialists.build
    @specialist.capacities.build
    @specialist.offices.build
    @specialization_clinics = @specialization.clinics.collect { |clinic| [clinic.name, clinic.id] }.sort
    @specialist_clinics = @specialist.clinics.collect {|c| c.id}    
  end

  def create
    @specialist = Specialist.new(params[:specialist])
    if @specialist.save!
      redirect_to @specialist, :notice => "Successfully created specialist. #{undo_link}"
    else
      render :action => 'new'
    end
  end

  def edit
    @specialization = Specialization.find(params[:specialization_id])
    @specialist = Specialist.find(params[:id])
    if @specialist.capacities.count == 0
      @specialist.capacities.build
    end
    @specialization_clinics = @specialization.clinics.collect { |clinic| [clinic.name, clinic.id] }.sort
    @specialist_clinics = @specialist.clinics.collect {|c| c.id}
  end

  def update
    @specialist = Specialist.find(params[:id])
    if @specialist.update_attributes!(params[:specialist])
      redirect_to @specialist, :notice => "Successfully updated specialist. #{undo_link}"
    else
      render :edit
    end
  end

  def destroy
    @specialist = Specialist.find(params[:id])
    @specialist.destroy
    redirect_to specialists_url, :notice => "Successfully destroyed specialist. #{undo_link}"
  end

  def undo_link
    view_context.link_to("undo", revert_version_path(@specialist.versions.scoped.last), :method => :post).html_safe
  end

  def email
    @specialist = Specialist.find params[:id]
    SpecialistMailer.invite_specialist(@specialist).deliver
    @contact = @specialist.contacts.build(:user_id => current_user, :notes => @specialist.contact_email)
    @contact.save
    redirect_to @specialist, :notice => "Sent email to #{@specialist.contact_email}"
  end
  
end

app/helpers/specialists_helper.rb
module SpecialistsHelper
end

app/views/specialists/_form.html.haml
-# a bit messy, and probably there is a better way of handling multiple controllers reusing this form
- form_method    = params[:action]     == 'new' ? :post   : :put
- current_action = params[:action]     == 'new' ? :create : :update
- form_action    = params[:controller] == 'specialists_editor' ? :update : current_action

= simple_nested_form_for @specialist, :url => {:controller => params[:controller], :action => form_action}, :method => form_method do |f|
  = f.error_messages
  - if @view
    .error_messages
      %h2 You are editing your record in the Fraser NW Division of Family Practice Resource database
      %p This database exists to make our practices, and your practice more efficient. By providing the information requested below you are making it easier for family doctors to find your practice, ensure that they are providing you with the correct information, and that your scope of practice is fully understood.

  %fieldset
    %h2 
      Specialist: 
      =@specialization.name
    = f.input :firstname, label: 'First Name'
    = f.input :lastname, label: 'Last Name'
    = f.input :direct_phone, label: "Direct Number (for physician contact)"

  %fieldset.office
    %h2 Office / Contact Information
    = f.simple_fields_for :offices do |i|
      %h4.location_header Location 1
      = i.input :phone1, label: "Phone"
      = i.input :fax

      = i.input :address1, label: "Street Address"
      = i.input :address2, label: "Suite"
      = i.input :city
      = i.input :province
      = i.input :postalcode, label: "Postal Code"
      %hr
    = f.link_to_add "Add a second office", :offices, class: "button", id: "add_office"

  - if current_user && current_user.admin?    
    %fieldset
      %h2 Senior MOA Contact Information
      %p Allows specialists to edit their own form. This information is only visible to admins.
      = f.input :contact_name, label: "Name"
      = f.input :contact_email, label: "Email"
      = f.input :contact_phone, label: "Phone"
      = f.input :contact_notes, label: "Notes", hint: "Include contact's role (MOA, etc.) and anything else we should know."

  %fieldset
    %h2 Status
    = f.input :status_mask, as: :select, collection: Specialist::STATUS_HASH, label: "Current Status", label_method: :last, value_method: :first
    = f.input :status_details, label: "Additional Details (if any)"
    = f.input :practise_limitations, label: "Other practice Limitations (if any)"
    = f.input :location_opened, label: "Practice opened at this location", as: :select, collection: ["Prior to 2010", 2010, 2011], prompt: "Select ..."

  %fieldset
    %h2 Areas of Practice
    %p
      In addition to history, PH, meds, allergies and previous OR/consultation reports, the following information/investigations are required for ALL patients.
      %span.quiet eg. XRs, MRIs, scans, blood work, etc.
    = f.input :required_investigations, label: false, input_html: { class: "full" }
    
    %h3 Pertinent Areas of Practice/Expertise
    %div.nested
      %p
        %span.first Referrals accepted in the following areas of practise.
        %span.last Additional information/investigations required for the specified area of practice.

      = f.simple_fields_for :capacities do |i|
        = i.association :procedure, as: :select, label: false, collection: @specialist.specialization.procedures.done_by_specialists, prompt: 'Select ...', wrapper: false
        = i.input :investigation, label: false, wrapper: false
        = i.hidden_field :_destroy
        = i.link_to_remove "remove"
      = f.link_to_add "Add an area of practice", :capacities, class: "button"

    %hr

    = f.input :interest, as: :text, label: "I am most interested in"
    = f.input :not_performed, as: :text, label: "I do not see or do"

  %fieldset.referral_details
    %h2 Referral Details
    .mechanisms
      %span.label How does your office accept requests for standard referrals?
      = f.input :referral_fax, as: :boolean, label: "Fax", wrapper: false
      = f.input :referral_phone, as: :boolean, label: "Phone", wrapper: false
      = f.input :referral_other_details, label: "Other", wrapper: false

    = f.input :referral_form, label: "Does your office have a referral form?", as: :radio
    .input.optional
      = f.input :lagtime, label: "Average length of time to notify GP of a booking date", as: :integer, input_html: {min: 0}, wrapper: false
      = f.input :lag_uom, label: false, wrapper: false, as: :select, collection: %w(days weeks months)
    
    .input.optional
      = f.input :waittime, label: "Average wait time from request for consultation to appointment", as: :integer, input_html: {min: 0}, wrapper: false
      = f.input :wait_uom, label: false, wrapper: false, as: :select, collection: %w(days weeks months)

    .mechanisms
      %span.label Our office will respond to referral requests
      %span.inputs
        To the referring office by:
        = f.input :respond_by_fax, as: :boolean, label: "Fax", wrapper: false
        = f.input :respond_by_phone, as: :boolean, label: "Phone", wrapper: false
        = f.input :respond_by_mail, as: :boolean, label: "Mail", wrapper: false
        %br
        = f.input :respond_to_patient, as: :boolean, label: "Directly to patient", wrapper: false
    = f.input :patient_can_book, as: :radio, label: "After you receive our referral, will your office accept direct calls from patients to book their own appointments?"
    = f.input :red_flags, label: "What conditions (red flags) does your office feel warrant urgent consultation?", as: :text, input_html: { class: "full" }
    .mechanisms
      %span.label Optimal method of referral for urgent appointments
      = f.input :urgent_fax, as: :boolean, label: "Fax", wrapper: false
      = f.input :urgent_phone, as: :boolean, label: "Phone", wrapper: false
      = f.input :urgent_other_details, label: "Other", wrapper: false

  %fieldset
    %h2 Hospital Privileges
    = f.association :hospitals, as: :check_boxes, label: false
    = link_to "Add a Hospital", new_hospital_path, class: "button"

  %fieldset
    %h2 Sub-Specialty Clinics
    = f.association :clinics, as: :check_boxes, label: false, collection: @specialization_clinics
    = link_to "Add a Clinic", new_specialization_clinic_path(@specialization), class: "button"


  -# FIXME - This shouldn't be in the view. Should be set by parent resource in controller.
  %p
    = f.input :specialization_id, as: :hidden

  = f.submit

app/views/specialists/edit.html.haml
- title "Edit #{@specialist.name} - #{@specialist.specialization.name}"

= render 'specialists/form'
= link_to "cancel", @specialist

app/views/specialists/index.html.haml
- title "Specialists - #{@specialization.name}"

/ - @specializations.each do |specialization|
/ # %h3= @specialization.name
%ul
  - @specialization.specialists.each do |specialist|
    %li= link_to listed_specialist(specialist), specialization_specialist_path(@specialization, specialist)

  / %td= link_to 'Show', specialist
  / %td= link_to 'Edit', edit_specialist_path(specialist)
  / %td= link_to 'Destroy', specialist, :confirm => 'Are you sure?', :method => :delete


/ %table
/   %tr
/     %th Firstname
/     %th Lastname
/     %th Address1
/     %th Address2
/     %th Postalcode
/     %th City
/     %th Province
/     %th Phone1
/     %th Fax
/     %th Status
/     %th Interest
/     %th Waittime
/     %th Specialization
/   - for specialist in @specialists
/     %tr
/       %td= specialist.firstname
/       %td= specialist.lastname
/       %td= specialist.address1
/       %td= specialist.address2
/       %td= specialist.postalcode
/       %td= specialist.city
/       %td= specialist.province
/       %td= specialist.phone1
/       %td= specialist.fax
/       %td= specialist.status
/       %td= specialist.interest
/       %td= specialist.waittime
/       %td= specialist.specialization_id

%p= link_to "New Specialist", new_specialization_specialist_path

app/views/specialists/new.html.haml
- title "New Specialist in #{@specialization.name}"

= render 'form'

%p= link_to "Back to List", specialists_path

app/views/specialists/show.html.haml
/ - title "Specialist"

- if @is_version
  = render 'versions/info'

/
  - if current_user.admin?
    #flash_notice
      - if @specialist.contact_email
        %h2 Email an invitation to this specialist
        %p Clicking the below link will send an invitation to edit this record with the following special url.
        %p= specialist_self_edit_path(@specialist, @specialist.token, :only_path => false)
        %p=link_to "Email #{@specialist.contact_email}", specialist_email_path(@specialist), :method => :post
      - else
        %p To send this link with an invitation to #{link_to "edit", edit_specialization_specialist_path(@specialist.specialization, @specialist)} this specialist and add contact information
      %h4
        This specialist was contacted through the application
        = "never" if @specialist.contacts.length < 1
      = render @specialist.contacts

%h1
  = @specialist.name
%h2
  = @specialist.specialization.name
%h3 
  = @specialist.offices[0].full_address
  
#phone 
  %strong Phone:
  = @specialist.offices[0].phone1.presence || "unknown"
#fax.collapseup 
  %strong Fax:
  = @specialist.offices[0].fax.presence || "unknown"
#direct_contact.collapseup
  %strong Direct number (for physician contact):
  = @specialist.direct_phone.presence || "none"


- if @specialist.offices[1] and @specialist.offices[1].exists?
  #address2
    %strong Second office:
    = @specialist.offices[1].full_address
  #phone2.collapseup 
    %strong Phone:
    = @specialist.offices[1].phone1.presence || "unknown"
  #fax2.collapseup
    %strong Fax:
    = @specialist.offices[1].fax.presence || "unknown"
  
  
- if @specialist.status.presence
  #status
    %strong Status:
    = @specialist.status
- if @specialist.status_details.presence
  #status_details.collapseup
    %strong Details: 
    = @specialist.status_details
- if @specialist.practice_limitations.presence
  #practice_limitations.collapseup
    %strong Practice limitations: 
    = @specialist.practice_limitations


#referrals_via
  %strong Accepts referrals via:
  = @specialist.accepts_referrals_via
#referral_form.collapseup
  %strong Has referral form:
  = @specialist.referral_form ? "yes" : "no"
#responds_via.collapseup
  %strong Responds via:
  = @specialist.responds_via
  
#lag_time
  %strong Average length of time to notify GP of a booking date:
  = @specialist.lagtime_with_units
#wait_time.collapseup
  %strong Average patient wait time until appointment date:
  = @specialist.waittime_with_units
#patient_can_bokok.collapseup
  %strong Patient can book after referral:
  = @specialist.patient_can_book ? "yes, after referral this office accepts direct calls from patients to book their appointments" : "no, this office does not accept direct calls from patients"

    
#red_flags
  %strong Conditons this office feels warrants urgent consultation:
  = @specialist.red_flags.presence || "unspecified"
#urgent_referral_via.collapseup
  %strong Accepts urgent referrals via:
  = @specialist.urgent_referrals_via
  

#referral_investigations
  %strong Required investigations:
  %span In addition to history, PH, medications, allergies, and previous OR and consultation reports, this office requires the following for all patients:
  = @specialist.required_investigations.presence || "none"
#scope.collapse_up
  %strong Scope of practice (with additional required investigations):
  = procedures_investigations_list(@specialist).html_safe
  
  
#interested
  %strong Interested in: 
  = @specialist.interest.presence || "unspecified" 
#not_interested.collapseup
  %strong Not interested in: 
  = @specialist.not_interested.presence || "unspecified"  
  
  
#hospitals
  %strong Hospital privileges: 
  - if @specialist.hospitals.empty? 
    none
  - else 
    - @specialist.hospitals.each do |hospital|
      = link_to(hospital.name, url_for(hospital)) + ", "
  
  
#clinics
  %strong Works at clinics: 
  - if @specialist.clinics.empty? 
    none
  - else 
    - @specialist.clinics.each do |clinic|
      = link_to(clinic.name, url_for(clinic)) + ", "
#edit
  = link_to "History", show_versions_path(@specialist)
  |
  - if can? :update, @specialist
    = link_to "Edit", edit_specialization_specialist_path(@specialist.specialization, @specialist)
    |
  - if can? :destroy, @specialist
    = link_to "Destroy", @specialist, :confirm => 'Are you sure?', :method => :delete
    |
  = link_to "View All #{@specialist.specialization.name}", specialization_path(@specialist.specialization)
  / |
  / # = link_to "View All Specialists", specialists_path