config/routes.rb
Frasernw::Application.routes.draw do

  resources :reviews, :only => [:index, :destroy] do
    put :accept
  end

  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  match "/versions"                 => "versions#show_all", :as => "all_versions"
  match "/specialists/:id/versions" => "versions#index",    :as => "show_versions", :model => 'specialists'
  match "/versions/:id"             => "versions#show",     :as => "show_version"

  resources :specializations do
    resources :specialists
    resources :procedures
    resources :clinics
  end
  resources :clinics
  resources :specialists
  resources :procedures
  resources :hospitals

  match "tracker" => 'tracker#index', :as => 'tracker'
  
  match "specializations/:id/showalt" => 'specializations#showalt'
  
  match "specialists/:id/:token/edit"   => 'specialists_editor#edit',  :as => 'specialist_self_edit'
  put  "specialists/:id/:token/update" => 'specialists_editor#update', :as => 'specialist_self_update'
  post  "specialists/email/:id"         => 'specialists#email', :as => 'specialist_email'
  
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'login' => 'user_sessions#new', :as => :login

  resources :user_sessions

  resources :users

  match 'searchtree'  => 'searchdoc#tree',  :as => :searchtree
  match 'searchindex' => 'searchdoc#index', :as => :searchindex
  match 'navigation' => 'searchdoc#navigation', :as => :navigation

  root :to => 'specializations#index'

end

app/models/specialization.rb
class Specialization < ActiveRecord::Base
  attr_accessible :name
  has_paper_trail meta: { to_review: false }
  
  has_many :specialists
  has_many :clinics
  has_many :procedures

  default_scope order('name')

end

app/controllers/specializations_controller.rb
class SpecializationsController < ApplicationController
  load_and_authorize_resource

  def index
    @specializations = Specialization.all
  end

  def show
    @specialization = Specialization.find(params[:id])
    render :layout => false if request.headers['X-PJAX']
  end
  
  def showalt
    @specialization = Specialization.find(params[:id])
    render :layout => false if request.headers['X-PJAX']
  end
  

  def new
    @specialization = Specialization.new
  end

  def create
    @specialization = Specialization.new(params[:specialization])
    if @specialization.save
      redirect_to @specialization, :notice => "Successfully created specialization."
    else
      render :action => 'new'
    end
  end

  def edit
    @specialization = Specialization.find(params[:id])
  end

  def update
    @specialization = Specialization.find(params[:id])
    if @specialization.update_attributes(params[:specialization])
      redirect_to @specialization, :notice  => "Successfully updated specialization."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @specialization = Specialization.find(params[:id])
    @specialization.destroy
    redirect_to specializations_url, :notice => "Successfully destroyed specialization."
  end
end

app/helpers/specializations_helper.rb
module SpecializationsHelper
end

app/views/specializations/_form.html.haml
= form_for @specialization do |f|
  = f.error_messages
  %p
    = f.label :name
    %br
    = f.text_field :name
  %p
    = f.submit

app/views/specializations/edit.html.haml
- title "Edit Specialization"

= render 'form'

%p
  = link_to "Show", @specialization
  |
  = link_to "View All", specializations_path

app/views/specializations/index.html.haml
%p= link_to "Add new specialty", new_specialization_path

app/views/specializations/new.html.haml
- title "New Specialization"

= render 'form'

%p= link_to "Back to List", specializations_path

app/views/specializations/show.html.haml
/- title "Specialities - " + @specialization.name

%h1= @specialization.name

%h2 Specialists &amp; Clinics

- items = { "Specialist" => @specialization.specialists, "Clinic" => @specialization.clinics }

- items.each_pair do |k,v|
    %table{:class => 'tablesorter {sortlist: [[0,0]]}'}
        - if not v.empty?
            %thead
                %tr
                    %th{:class => "{sorter: 'bylastname'} name_coumn"}= k
                    %th{:class => "{sorter: 'waittime'} number_column"} Wait Time
                    %th{:class => "{sorter: 'blanks_to_bottom'} city_column"} City
            %tbody
                - v.each do |specialist|
                    %tr
                        %td.name_column
                            - case k
                                - when 'Specialist'
                                    = link_to specialist.name, specialization_specialist_path(@specialization, specialist)
                                - when 'Clinic'
                                    = link_to specialist.name, specialization_clinic_path(@specialization, specialist)
                        %td.number_column= specialist.waittime_with_units
                        / FIXME - make a clink to specialists from a certain city
                        / %td= link_to "#{specialist.city}", specialization_city_path(@specialization, specialist.city)
                        %td.city_column= specialist.city

%p
    = link_to "New clinic", new_specialization_clinic_path(@specialization)
    |
    = link_to "New specialist", new_specialization_specialist_path(@specialization)
    |
    = link_to "New Area of Practise", new_specialization_procedure_path(@specialization)

%p
    = link_to "Edit", edit_specialization_path(@specialization)
    |
    = link_to "Destroy", @specialization, :confirm => 'Are you sure?', :method => :delete
    |
    = link_to "View All", specializations_path

app/views/specializations/showalt.html.haml
/ - title "Specialization"

%h1= @specialization.name

%h3 Specialists

%table{:class => 'grid', :id => 'specialist_table'}
  %tr
    %th Name
    %th Wait (weeks)
    %th City
    %th Interests/Expertise
    %th Scope of practice
  - @specialization.specialists.each do |specialist|
    %tr
      %td= link_to "#{specialist.firstname} #{specialist.lastname}", specialization_specialist_path(@specialization, specialist)
      %td= link_to "#{specialist.waittime}"
      %td= link_to "#{specialist.city}"
      %td= link_to "#{specialist.interest}"
      %td= specialists_procedures(specialist)
      

/ %ul
/   - @specialization.specialists.each do |specialist|
/     %li= link_to listed_specialist(specialist), specialization_specialist_path(@specialization, specialist)

%h3 Scope of practice
%ul
  - @specialization.procedures.each do |procedure|
    %li= link_to listed_procedure(procedure), specialization_procedure_path(@specialization, procedure)

%p
  = link_to "New specialist", new_specialization_specialist_path(@specialization)
  |
  = link_to "New procedure", new_specialization_procedure_path(@specialization)

%p
  = link_to "Edit", edit_specialization_path(@specialization)
  |
  = link_to "Destroy", @specialization, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", specializations_path