config/routes.rb
Frasernw::Application.routes.draw do

  resources :reviews, :only => [:index, :destroy] do
    put :accept
  end

  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  match "/versions"                 => "versions#show_all", :as => "all_versions"
  match "/specialists/:id/versions" => "versions#index",    :as => "show_versions", :model => 'specialists'
  match "/versions/:id"             => "versions#show",     :as => "show_version"

  resources :specializations do
    resources :specialists
    resources :procedures
    resources :clinics
  end
  resources :clinics
  resources :specialists
  resources :procedures
  resources :hospitals

  match "tracker" => 'tracker#index', :as => 'tracker'
  
  match "specializations/:id/showalt" => 'specializations#showalt'
  
  match "specialists/:id/:token/edit"   => 'specialists_editor#edit',  :as => 'specialist_self_edit'
  put  "specialists/:id/:token/update" => 'specialists_editor#update', :as => 'specialist_self_update'
  post  "specialists/email/:id"         => 'specialists#email', :as => 'specialist_email'
  
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'login' => 'user_sessions#new', :as => :login

  resources :user_sessions

  resources :users

  match 'searchtree'  => 'searchdoc#tree',  :as => :searchtree
  match 'searchindex' => 'searchdoc#index', :as => :searchindex
  match 'navigation' => 'searchdoc#navigation', :as => :navigation

  root :to => 'specializations#index'

end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
  attr_accessible :name, :specialization_id, :done_by_specialists, :done_by_clinics
  has_paper_trail

  has_many :capacities
  has_many :specialists, :through => :capacities
  
  has_many :focuses
  has_many :clinics, :through => :focuses
  
  belongs_to :specialization

  default_scope :order => 'name ASC'

  validates_presence_of :specialization_id, :on => :save, :message => "can't be blank"
  validates_presence_of :name, :on => :save, :message => "can't be blank"

  scope :done_by_specialists, where(:done_by_specialists  => true)
  
  def to_s
    self.name
  end

end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  load_and_authorize_resource

  def index
    if params[:specialization_id] != nil
      @specialization = Specialization.find params[:specialization_id]
      @procedures = @specialization.procedures
      redirect_to specialization_procedures_path(@specialization, @specialization.procedures) and return
    else
      redirect_to specialization_path(@specialization) and return
    end
  end

  def show
    @procedure = Procedure.find(params[:id])
    if request.headers['X-PJAX']
      render :layout => false
    end
  end

  def new
    @specialization = Specialization.find(params[:specialization_id])
    @procedure = Procedure.new :specialization_id => @specialization.id
  end

  def create
    @procedure = Procedure.new(params[:procedure])
    if @procedure.save
      redirect_to @procedure, :notice => "Successfully created scope of practice."
    else
      render :action => 'new'
    end
  end

  def edit
    @procedure = Procedure.find(params[:id])
  end

  def update
    @procedure = Procedure.find(params[:id])
    if @procedure.update_attributes(params[:procedure])
      redirect_to @procedure, :notice  => "Successfully updated scope of practice."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @procedure = Procedure.find(params[:id])
    @procedure.destroy
    # redirect_to '/specializations', :notice => "Successfully destroyed scope of practice."
    redirect_to procedures_url, :notice => "Successfully destroyed procedure."
  end
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/views/procedures/_form.html.haml
= form_for @procedure do |f|
  = f.error_messages
  %p
    = f.label :name
    %br
    = f.text_field :name
  %p
    = f.label :done_by_specialists
    %br
    = f.check_box :done_by_specialists
  %p
    = f.label :done_by_clinics
    %br
    = f.check_box :done_by_clinics
    = f.hidden_field :specialization_id
  %p
    = f.submit "Update Scope"

app/views/procedures/edit.html.haml
- title "Edit Scope of Practice"

= render 'form'

%p
  = link_to "Show", @procedure

app/views/procedures/index.html.haml
/ - title "Scopes of practice - #{@specialization.name}"

%h1= @specialization.name
%ul
  - @specialization.procedures.each do |procedure|
    %li= link_to procedure.name, procedure

%p= link_to "New scope of practice", new_specialization_procedure_path(@specialization)

app/views/procedures/new.html.haml
- title "New scope of practice in #{@specialization.name}"

= render 'form'

%p= link_to "Back to List", procedures_path

app/views/procedures/show.html.haml
/ - title "Scope of practice"

/ FIXME, this should iterate through @procedure's specializations
%h1
    = @procedure.name + ' - ' + @procedure.specialization.name
%h2 Specialists and Clinics

- items = { "Specialist" => @procedure.specialists, "Clinic" => @procedure.clinics }

%table{:class => 'tablesorter {sortlist: [[0,0]]}', :id => 'specialist_table'}
    - items.each_pair do |k,v|
        - if not v.empty?
            %thead
                %tr
                    %th{:class => "{sorter: 'bylastname'} name_column"}= k
                    %th{:class => "{sorter: 'waittime'} number_column"} Wait Time
                    %th{:class => "{sorter: 'blanks_to_bottom'} city_column"} City
            %tbody
                - v.each do |specialist|
                    %tr
                        %td.name_column
                            - case k
                                - when 'Specialist'
                                    = link_to specialist.name, specialization_specialist_path(@procedure.specialization, specialist)
                                - when 'Clinic'
                                    = link_to specialist.name, specialization_clinic_path(@procedure.specialization, specialist)
                        %td.number_column= specialist.waittime_with_units
                        / FIXME - make a clink to specialists from a certain city
                        / %td= link_to "#{specialist.city}", specialization_city_path(@specialization, specialist.city)
                        %td.city_column= specialist.city


%p
    = link_to "Edit", edit_procedure_path(@procedure)
    |
    = link_to "Destroy", @procedure, :confirm => 'Are you sure?', :method => :delete
    |
    = link_to "View All #{@procedure.specialization.name}", specialization_path(@procedure.specialization)
    / |
    / |
    / #= link_to "View All", procedures_path